FROM node:18-alpine as BUILD_IMAGE

WORKDIR /app

COPY package.json yarn.lock ./

RUN corepack enable

RUN yarn install

COPY . .

RUN yarn build

FROM node:18-alpine as PRODUCTION_IMAGE

WORKDIR /app

COPY package.json yarn.lock ./

COPY vite.config.ts .

RUN yarn add typescript

COPY --from=BUILD_IMAGE /app/dist /app/dist

CMD [ "yarn", "preview" ]
